# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170219_2123'),
        ('courses', '0003_auto_20170203_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coures_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
