# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_skills',
            field=models.CharField(default='', max_length=200, verbose_name='\u6280\u80fd\u83b7\u53d6'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
